version: "3.8"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: financialmanager
      POSTGRES_PASSWORD: financialmanager
    volumes:
      - financialmanager_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  financialmanager_volume:
